
services:
  # LocalStack for AWS service emulation
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - checkin-network


  # Mock Authentication Server
  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
    container_name: checkin-auth-server
    ports:
      - "3001:3001"
    env_file:
      - auth-server/env.example
    depends_on:
      - localstack
    networks:
      - checkin-network

networks:
  checkin-network:
    driver: bridge

volumes:
  localstack_data: 